name: Build image
on: [push]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            latest
            ${{ github.run_number }}
          containerfiles: |
            ./Containerfile

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        if: github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE }}
          tags: |
            latest
            ${{ github.run_number }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

  build-test:
    name: Build test image (no quadlets)
    runs-on: ubuntu-24.04-arm
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v7

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            test
            test-${{ github.run_number }}
          build-args: |
            ENABLE_QUADLETS=0
          containerfiles: |
            ./Containerfile

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE }}
          tags: |
            test
            test-${{ github.run_number }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
